Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 135
  Exclude:
    - 'bin/bundle'

Metrics/MethodLength:
  Max: 75

Metrics/ClassLength:
  Max: 500

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 25

AllCops:
  NewCops: enable
  Exclude:
    - db/**