Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 130
  Exclude:
    - 'bin/bundle'

Metrics/MethodLength:
  Max: 75

Metrics/ClassLength:
  Max: 500

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 20

AllCops:
  NewCops: enable
  Exclude:
    - db/**