default: &default
  pilot_siat_codes_invoices_wsdl: 'https://pilotosiatservicios.impuestos.gob.bo/v2/FacturacionCodigos?wsdl'
  pilot_siat_sync_invoice_wsdl: 'https://pilotosiatservicios.impuestos.gob.bo/v2/FacturacionSincronizacion?wsdl'
  pilot_siat_computarized_invoice_service_wsdl: 'https://pilotosiatservicios.impuestos.gob.bo/v1/ServicioFacturacionComputarizada?wsdl'
  pilot_siat_sales_invoice_service_wsdl: 'https://pilotosiatservicios.impuestos.gob.bo/v2/ServicioFacturacionCompraVenta?wsdl'
  pilot_siat_operations_invoice_wsdl: 'https://pilotosiatservicios.impuestos.gob.bo/v2/FacturacionOperaciones?wsdl'
  pilot_siat_url: 'https://pilotosiat.impuestos.gob.bo/consulta/QR'

  siat_codes_invoices_wsdl: 'https://pilotosiatservicios.impuestos.gob.bo/v2/FacturacionCodigos?wsdl'
  siat_sync_invoice_wsdl: 'https://pilotosiatservicios.impuestos.gob.bo/v2/FacturacionSincronizacion?wsdl'
  siat_computarized_invoice_service_wsdl: 'https://pilotosiatservicios.impuestos.gob.bo/v1/ServicioFacturacionComputarizada?wsdl'
  siat_sales_invoice_service_wsdl: 'https://pilotosiatservicios.impuestos.gob.bo/v2/ServicioFacturacionCompraVenta?wsdl'
  siat_operations_invoice_wsdl: 'https://pilotosiatservicios.impuestos.gob.bo/v2/FacturacionOperaciones?wsdl'
  siat_url: 'https://pilotosiat.impuestos.gob.bo/consulta/QR'

  siat_namespace: 'https://siat.impuestos.gob.bo/'

development:
  <<: *default

production:
  <<: *default